---
site_name: "Information Resource Registry Model Documentation"
theme:
  name: material
  palette:
    scheme: black
    primary: black
  logo: images/biolink-logo.png
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Overview: index.md
  - Infores Identifier Registry: information-resource-registry.md
site_url: https://biolink.github.io/information-resource-registry
repo_url: https://github.com/biolink/information-resource-registry
extra_css:
  - style.css
extra:
  analytics:
    provider: google
    property: G-J23SCD6JB8

