[tool.poetry]
name = "information-resource-registry"
version = "0.0.0"
description = "A registry of information resources used in NCATS Data Translator"
authors = ["Sierra Moxon <smoxon@lbl.gov>"]
license = "MIT"
readme = "README.md"
include = ["README.md", "src/information-resource-registry/schema", "project", "src/information-resource-registry/datamodel", "src/information-resource-registry/scripts"]

[tool.poetry.scripts]
add_consume_info = "src.information-resource-registry.relation-map.src.add_consume_info:add_consume_info"
aragorn_kps = "src.information-resource-registry.relation-map.src.aragorn_kps:aragorn_kps"
arax_kps = "src.information-resource-registry.relation-map.src.arax_kps:arax_kps"
bte_sp = "src.information-resource-registry.relation-map.src.bte_sp:bte_sp"
extract_consume_info = "src.information-resource-registry.relation-map.src.extract_consume_info:extract_consume_info"
generate_sankey = "src.information-resource-registry.relation-map.src.generate_sankey:generate_sankey"
molepro_consume = "src.information-resource-registry.relation-map.src.molepro_consume:molepro_consume"
rtx_kg2 = "src.information-resource-registry.relation-map.src.rtx_kg2:rtx_kg2"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry.dependencies]
python = "^3.10"
curies = "^0.7.4"
prefixmaps = "^0.2.0"
pyyaml = "^6.0.1"
stringcase = "^1.2.0"
pytest = "^7.3.1"
beautifulsoup4 = ">=4.0.0"

[tool.poetry.dev-dependencies]
linkml = ">=1.6.3"
mkdocs = "^1.4.2"
mkdocs-material = "^9.4.8"
mkdocs-mermaid2-plugin = "^1.1.1"
schemasheets = "^0.1.14"
codespell = "^2.2.6"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.extras]
docs = ["mkdocs-material"]

[tool.codespell]
skip = '.idea,.git,SEMMEDDB*,semmed*,*.svg,docs'
ignore-words-list = 'amination,ehr,mor,brite,nin,mirgate,MiRgate,EHR,nin,miR,miRNA,miRBase'
