---
name: Codespell

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    types: trigger-codespell

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
        with:
          ignore_words_list: brite,BRITE
          skip: .idea,.venv,.git,*.pdf,*.svg,context.*,project