---
name: Codespell

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    types: trigger-codespell

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
        with:
          skip: '.idea,.git,SEMMEDDB*,semmed*,*.svg,docs'
          ignore-words-list: 'amination,ehr,mor,brite,nin,mirgate,MiRgate,EHR,nin,miR,miRNA,miRBase'