name: Check Infores Catalog Links
on:
  pull_request:
  schedule:
    - cron: '0 5 * * 1'  # at 05:00 UTC every Monday
  workflow_dispatch:

jobs:
  check-external-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install 

      - name: Run URL validation
        run: |
          make validate_infores

      - name: Regenerate Sankey
        run: |
          make sankey